update Chinese translation file and change Chinese mod name
CyclopsMC/IntegratedDynamics pull request #577
Opened 2018-05-20 06:04 UTC by Flithor

2018-05-20 06:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CyclopsMC/IntegratedDynamics?pullRequest=577) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CyclopsMC/IntegratedDynamics?pullRequest=577) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CyclopsMC/IntegratedDynamics?pullRequest=577) it.</sub>

2018-05-20 06:27 UTC, rubensworks requested changes
Please don't change English to Chinese...

2018-05-21 03:11 UTC, Flithor commented
Oh, sorry for my mistake

2018-05-21 08:03 UTC, merged

2018-05-21 08:03 UTC, rubensworks commented
Thanks!