Random functions, Absolute
CyclopsMC/IntegratedDynamics pull request #745
Opened 2019-06-23 20:42 UTC by slyons

This PR adds the following functionality:

* `rand` -> Random from zero to any number type
* `rand2` -> Random from any number to any number (result is type of the second)
* `randElem` -> Random element from a list
* `randBool` -> Random boolean
* `abs` -> Absolute value of a number type

It's in need of a pass to make sure it fully conforms with the rest of the library design, but tests are included for each one and they've been tested in-world.

2019-06-23 20:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CyclopsMC/IntegratedDynamics?pullRequest=745) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CyclopsMC/IntegratedDynamics?pullRequest=745) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CyclopsMC/IntegratedDynamics?pullRequest=745) it.</sub>

2019-06-24 14:56 UTC, rubensworks commented
Thanks! I'll try to look into this asap.

It looks like Travis is failing on the unit tests though.

2019-06-24 17:05 UTC, slyons commented
@rubensworks I'm a bit confused by the Travis failure, I'm not seeing that exception locally. 

```
org.cyclops.integrateddynamics.core.evaluate.variable.TestGeneralOperators > testRandMixedTypes FAILED
    org.cyclops.integrateddynamics.api.evaluate.variable.IValueCastRegistry$ValueCastException at TestGeneralOperators.java:249
```
I'm not seeing the actual exception message so I can diagnose it. In this test in particular an Integer variable is cast to a Double, which is a valid no-loss operation in Java, but I'm guessing not in the evaluation engine.

2019-06-24 17:57 UTC, rubensworks commented
Not sure what is going on there. Might be a Java compiler difference (Travis is using oraclejdk8).

2019-06-26 17:54 UTC, slyons commented
@rubensworks I just modified the randRange bit to require same types. Worst case users should use the existing casting methods.

2019-06-29 12:28 UTC, rubensworks requested changes
I like the new `abs` operator, for which I just have a couple of minor comments.

However, I have some major concerns with the random-related operators.
The thing is, this mod assumes all operators to be fully deterministic (like most declarative programming languages).
These new operators unfortunately don't maintain this assumption.
Since ID makes use of this assumption for caching operator chains, this will likely break a lot of things.

I agree however that random value generation is useful, which is why a random aspect was added to the extradimensional reader, which is consistent with the deterministic nature of operators. If really needed, more random-related aspects could be added to the extradimensional reader.

2019-06-29 12:28 UTC, rubensworks commented on src/main/java/org/cyclops/integrateddynamics/core/evaluate/operator/Operators.java
> +    public static final IOperator NUMBER_ABSOLUTE = REGISTRY.register(OperatorBuilder
I would make this part of the `ARITHMETIC OPERATORS`.

Don't use `OperatorBuilder` directly, but create `OperatorBuilders.ARITHMETIC_1` (A variant of `OperatorBuilders.ARITHMETIC_2`).

Make sure to move this declaration to right after `ARITHMETIC_MINIMUM`.

2019-06-29 12:28 UTC, rubensworks commented on src/test/java/org/cyclops/integrateddynamics/core/evaluate/variable/TestGeneralOperators.java
> +    public void testAbsoluteDouble() throws EvaluationException {
Can you also add one for Long?

2019-06-29 12:28 UTC, rubensworks commented on src/test/java/org/cyclops/integrateddynamics/core/evaluate/variable/TestGeneralOperators.java
> +     * ----------------------------------- ABS -----------------------------------
Can you also add `testInvalidInputSizeIAbsLarge` and `testInvalidInputSizeAbsSmall` tests?
(For consistency with the unit tests for the other operators)

2019-08-02 13:04 UTC, rubensworks commented
@slyons I'm going to close this PR. I'm open to reusing your implementations in other ways in another PR though. Let's discuss on Discord if you're interested in this.

2019-08-02 13:04 UTC, closed without merging