Filter List for String values before joining
CyclopsMC/IntegratedDynamics pull request #789
Opened 2019-11-18 18:50 UTC by TomyLobo

I also replaced the string joining by a joining collector.

Fixes #783

2019-11-19 07:29 UTC, rubensworks requested changes
Not sure silently filtering away the non-string elements is the way to go here. Throwing an eval exception would be the preferred solution when such elements are encountered.

2019-11-19 18:37 UTC, TomyLobo commented
@rubensworks I changed it as requested.
And I noticed that correspondTo needs some work.
It's not clear whether it's a necessary or a sufficient criterion for casting everything to string.
Apparently it's only a necessary criterion. That should be documented or the function be given a better name.

Btw, I see a ton of unchecked generics everywhere I look.
That's a ticking time bomb, you basically have no way of telling whether an inocuous assignment somewhere will throw a ClassCastException resulting from an invalid unchecked cast somewhere else.

2019-11-19 18:41 UTC, rubensworks requested changes
Thanks for the change, but I feel like this is becoming too complex for what it is.
The code will now be iterating the list two times in regular cases, which is not needed.

What about using a single simple for-loop instead?

2019-11-19 18:42 UTC, rubensworks commented
> And I noticed that correspondTo needs some work.

> Btw, I see a ton of unchecked generics everywhere I look.

PRs for improvements are always welcome.

2019-11-19 19:27 UTC, TomyLobo commented
> 
> 
> Thanks for the change, but I feel like this is becoming too complex for what it is.
> The code will now be iterating the list two times in regular cases, which is not needed.
> 
> What about using a single simple for-loop instead?

If you want to cut down on CPU cycles, keep in mind that your original code already iterated this twice: Once to create the list and another time to join it.

If you want to cut down code, a more effective approach would be to "correspondsTo" if block, as that no longer catches anything that isn't already caught later.

2019-11-22 19:58 UTC, rubensworks commented
I went for a different solution (d0963292bdc3c5af4a2b43d12caefb6cb9afe7a8) that has a lower computational complexity.
Thanks in any case for the PR!

2019-11-22 19:58 UTC, closed without merging